spring:
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
website:
  markdownDir: E:/demo/articles
  indexDir: d:/website/index
  articleTitle: FILE_NAME
server:
  port: 9999

