spring:
  thymeleaf:
    cache: false
website:
  markdownDir: E:/demo/articles
  indexDir: d:/website/index
  articleTitle: FILE_NAME
  about: About.md
  page:
    pageSize: 10
    newesetSize: 5
    author: Aladi
    logo: '<img class="align-bottom" src="/bug32.png"/><img src="/cat48.png">不能约的Secret'
    footer: '&copy; Aladi 2018 <br/>
     <a href="https://github.com/234369425/Markdown-Blog" target="_blank">
     <img src="/cat32.png"><span class="badge badge-primary">Markdown blog，welcome join</a></span>'
    keywords: ''
    titleSuffix: '个人随笔'

  gittalk:
    owner:
    repo:
    oauth:
      clientId:
      secret:
server:
  port: 9999

