spring:
  datasource:
    url: jdbc:mysql://localhost/website?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
website:
  markdownDir: E:/demo/articles
  indexDir: d:/website/index
  articleTitle: FILE_NAME
  about: About.md
  page:
    pageSize: 10
    newesetSize: 5
    author: Aladi
    logo: '不能约的Secret'
    footer: '&copy; Aladi 2018 <br/>
     <a href="https://github.com/234369425/snow" target="_blank">
     <span class="badge badge-primary">Markdown blog，welcome join</a></span>'
  gittalk:
    owner:
    repo:
    oauth:
      clientId:
      secret:
server:
  port: 9999

