spring:
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
website:
  markdownDir: E:/git/KoDiRemoteControl
  indexDir: d:/website/index
